export const skills = [
    {
        titleKey: 'skills.frontend',
        descKey: 'skills.frontend.desc',
        tags: [
            'React',
            'React Hooks',
            'Vue',
            'TypeScript',
            'Three.js',
            'Monorepo',
            'SSR',
            { zh: '微信小程序', en: 'WeChat Mini Programs' },
            { zh: 'uni-app / Taro 跨端', en: 'uni-app / Taro Cross-platform' },
            { zh: 'ECharts', en: 'ECharts' },
            { zh: '微前端', en: 'Micro Frontends' },
        ],
    },
    {
        titleKey: 'skills.backend',
        descKey: 'skills.backend.desc',
        tags: [
            'Next.js (SSR)',
            'Nest.js',
            'Node.js',
            'Nginx',
            'MySQL',
            'Docker',
            'RESTful API',
            { zh: '服务部署', en: 'Service Deployment' },
            { zh: '权限体系', en: 'Permission System' },
        ],
    },
    {
        titleKey: 'skills.management',
        descKey: 'skills.management.desc',
        tags: [
            { zh: '技术规划', en: 'Tech Strategy' },
            { zh: '团队建设', en: 'Team Building' },
            { zh: '项目管理', en: 'Project Management' },
            { zh: '代码评审', en: 'Code Review' },
            { zh: '技术规范', en: 'Technical Standards' },
        ],
    },
];
